stuff_app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :payments
  resources :charges
  root to: "products#index"

end

stuff_app/app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
end

stuff_app/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :product
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal


 def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end

end

stuff_app/app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

stuff_app/app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

stuff_app/app/models/payment.rb
require 'net/http'
require 'uri'
class Payment < ActiveRecord::Base

validate :credit_card_api_access, :on => :create
MERCHANT_ID = "0000992"
INTEGRATION_URL = "https://gateway.cardstream.com/direct/"


end

stuff_app/app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items


end

stuff_app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

stuff_app/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

stuff_app/app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => 'example@stripe.com',
    :card  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to charges_path
end
end

stuff_app/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_orders, only: [:show, :edit, :update, :destroy]
  before_action :set_customers, only: [:show, :edit, :update, :destroy]
  before_action :set_products, only: [:show, :edit, :update, :destroy]



  def index
    @orders = Order.all
    @customers = Customer.all
    @products = Product.all
  end
  def new
    @orders = Order.new
  end

  def show
    @orders = Order.find(params[:id])
    @customers = Customer.find(params[:id])
    @products = Product.find(params[:id])
  end

  def create


    @order = Order.new(order_params) #(params[:prod_name, :description, :price])
    if @order.save(order_params)
       format.html { redirect_to orders_url, notice: 'orders was successfully created.' }
       #redirect_to "/orders"

      else
        format.html { render :new }
        format.json { render json: @orders.errors, status: :unprocessable_entity }

      end

      #binding.byebug
  end

  def update
    respond_to do |format|
      if @orders.update(order_params)
        format.html { redirect_to orders_url, notice: 'orders was successfully updated.' }

      else
        format.html { render :edit }

      end
    end
  end

  def edit
    @orders = Order.find(params[:id])

  end

  def destroy
    @orders.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'orders was successfully destroyed.' }
  end
  end



  private

  def order_params
    params.require(:order).permit(:customers_id, :products_id, :comment)
  end
  def set_orders
      @orders = Order.find(params[:id])
    end
    def customer_params
    params.require(:customer).permit(:name, :address, :city, :state, :zipcode, :phone)
  end
  def set_customers
      @customers = Customer.find(params[:id])
    end
    def product_params
    params.require(:product).permit(:prod_name, :description, :price)
  end
  def set_products
      @products = Product.find(params[:id])
    end


end

stuff_app/app/controllers/payments_controller.rb
require 'net/http'
require 'uri'


class PaymentsController < ApplicationController

require 'net/http'
require 'uri'

class Payment < ActiveRecord::Base

  attr_accessor :cardNumber, :cardCVV, :cardExpiryMonth, :cardExpiryYear,
  :responseMessage, :amount, :amountReceived, :cardNumber, :cardType, :cardTypeCode, :responseCode,    :transactionID, :xref, :cardNumber, :cardCVV, :cardExpiryMonth, :cardExpiryYear



  def index
    @payments = Payment.new(request_data)

  end


  MERCHANT_ID = "0000992"
  INTEGRATION_URL = "https://gateway.cardstream.com/direct/"

  def request_data
    {
      :amount => self.amount.to_i,
      :cardNumber => self.cardNumber,
      :cardExpiryMonth => self.cardExpiryMonth.to_i,
      :cardExpiryYear => self.cardExpiryYear.to_i,
      :cardCVV => self.cardCVV.to_i,
      :merchantID => MERCHANT_ID,
      :action => "SALE",
      :type => 1,
      :currencyCode => 826,
      :orderRef => "Test purchase",
      :countryCode => 826,
      :returnInternalData => "Y",
      :threeDSRequired => "N"
    }
  end

  def new
    @payments = Payment.new(request_data)
  end

  def create

    @payments = Payment.new(request_data) #(params[:prod_name, :description, :price])

  end



  def credit_card_api_access
    uri = URI.parse(INTEGRATION_URL)
    http = Net::HTTP.new(uri.host, 443)
    http.use_ssl = true
    req = Net::HTTP::Post.new(uri.request_uri)
    req.set_form_data(request_data)
    response = http.request(req)
    response_hash = Rack::Utils.parse_nested_query response.body
    if response_hash['responseCode'] != "0"
      errors.add(:id, "Payment failed #{response_hash['responseMessage']}")
    else
      self.attributes = strip_cc_response_hash(response_hash)
    end
  end

  def strip_cc_response_hash(hsh)
    hsh.each { |key,value| hsh.delete(key) unless Payment.column_names.include?(key)}
    return hsh
  end





end
end

stuff_app/app/helpers/application_helper.rb
module ApplicationHelper
end

stuff_app/app/helpers/carts_helper.rb
module CartsHelper
end

stuff_app/app/helpers/charges_helper.rb
module ChargesHelper
end

stuff_app/app/helpers/customers_helper.rb
module CustomersHelper
end

stuff_app/app/helpers/main_helper.rb
module MainHelper
end

stuff_app/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

stuff_app/app/helpers/orders_helper.rb
module OrdersHelper
end

stuff_app/app/helpers/payments_helper.rb
module PaymentsHelper

  def cc_years
    yrs = []
    year_today = Date.today.strftime("%y").to_i
    year_today.upto(year_today+10).each do |y| yrs << y.to_s;end
    return yrs
  end

  def cc_months
    ['01','02','03','04','05','06','07','08','09','10','11','12']
  end

end

stuff_app/app/helpers/products_helper.rb
module ProductsHelper
end

stuff_app/app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

stuff_app/app/views/layouts/_checkout_text.html.erb
<%= link_to "Checkout", payments_path, class: "btn btn-link" %>

stuff_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>STUFF for sale</title>

<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %>
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
   <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= stylesheet_link_tag    "application", :media => "all" %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1><%= link_to "STUFF", root_path %></h1>
      </div>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
        <h1 class="checkout"><%= render 'layouts/checkout_text' %></h1>
      </div>
    </div>
    <hr>
    <%= yield %>
  </div>

</body>
</html>

stuff_app/app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>