stuff_app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :payments
  resources :charges
  root to: "products#index"

end

stuff_app/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :product
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal


 def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end

end

stuff_app/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_orders, only: [:show, :edit, :update, :destroy]
  before_action :set_customers, only: [:show, :edit, :update, :destroy]
  before_action :set_products, only: [:show, :edit, :update, :destroy]



  def index
    @orders = Order.all
    @customers = Customer.all
    @products = Product.all
  end
  def new
    @orders = Order.new
  end

  def show
    @orders = Order.find(params[:id])
    @customers = Customer.find(params[:id])
    @products = Product.find(params[:id])
  end

  def create


    @order = Order.new(order_params) #(params[:prod_name, :description, :price])
    if @order.save(order_params)
       format.html { redirect_to orders_url, notice: 'orders was successfully created.' }
       #redirect_to "/orders"

      else
        format.html { render :new }
        format.json { render json: @orders.errors, status: :unprocessable_entity }

      end

      #binding.byebug
  end

  def update
    respond_to do |format|
      if @orders.update(order_params)
        format.html { redirect_to orders_url, notice: 'orders was successfully updated.' }

      else
        format.html { render :edit }

      end
    end
  end

  def edit
    @orders = Order.find(params[:id])

  end

  def destroy
    @orders.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'orders was successfully destroyed.' }
  end
  end



  private

  def order_params
    params.require(:order).permit(:customers_id, :products_id, :comment)
  end
  def set_orders
      @orders = Order.find(params[:id])
    end
    def customer_params
    params.require(:customer).permit(:name, :address, :city, :state, :zipcode, :phone)
  end
  def set_customers
      @customers = Customer.find(params[:id])
    end
    def product_params
    params.require(:product).permit(:prod_name, :description, :price)
  end
  def set_products
      @products = Product.find(params[:id])
    end


end

stuff_app/app/helpers/orders_helper.rb
module OrdersHelper
end

stuff_app/app/views/orders/_form.html.erb
<%= form_for(@orders) do |f| %>
  <% if @orders.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orders.errors.count, "error") %> prohibited this orders from being saved:</h2>

      <ul>
      <% @orders.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

stuff_app/app/views/orders/edit.html.erb
<h1>Editing Order</h1>


<%= render 'form' %>

<%= link_to 'Back', orders_path %>

stuff_app/app/views/orders/index.html.erb
<h1><%= Order%></h1>

<table class="table table-striped table-bordered">
<thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>zipcode</th>
      <th>Phone</th>
      <th>product</th>
      <th>description</th>
      <th>price</th>
      <th>comment</th>



      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |orders| %>
      <tr>
        <td><%= orders.customer.name %></td>
        <td><%= orders.customer.address %></td>
        <td><%= orders.customer.city %></td>
        <td><%= orders.customer.state %></td>
        <td><%= orders.customer.zipcode %></td>
        <td><%= orders.customer.phone %></td>
        <td><%= orders.product.prod_name %></td>
        <td><%= orders.product.description %></td>
        <td><%= orders.product.price %></td>
        <td><%= orders.comment %></td>



        <td><%= link_to 'Edit', edit_order_path(orders) %></td>






    <% end %>
  </tbody>
</table>

<p><%= link_to "Back to Stuff list", root_path %></p>

stuff_app/app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

stuff_app/app/views/orders/show.html.erb
  <h1><%= @orders.id %></h1>

  <h1><%= @customers.name %></h1>
  <h1><%= @products.prod_name%></h1>
  <h1><%= @products.description%></h1>
  <h1><%= @products.price %></h1>
  <h1><%= @orders.comment%></h1>

  <p><%= link_to "Back to Stuff list", root_path %></p>