stuff_app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :payments
  resources :charges
  root to: "products#index"

end

stuff_app/app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items


end

stuff_app/app/controllers/products_controller.rb
require 'byebug'
class ProductsController < ApplicationController
  before_action :set_products, only: [:show, :edit, :update, :destroy]
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def new
    @products = Product.new
  end

  def show
    @products = Product.find(params[:id])
  end

  def create

    @product = Product.new(product_params) #(params[:prod_name, :description, :price])
    if @product.save
      redirect_to "/products"

      else
        format.html { render :new }
        format.json { render json: @products.errors, status: :unprocessable_entity }

      end

      #binding.byebug
  end

  def update
    respond_to do |format|
      if @products.update(product_params)
        format.html { redirect_to products_url, notice: 'products was successfully updated.' }

      else
        format.html { render :edit }

      end
    end
  end

  def edit
    @products = Product.find(params[:id])

  end

  def destroy
    @products.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'products was successfully destroyed.' }
  end
  end



  private

  def product_params
    params.require(:product).permit(:prod_name, :description, :price)
  end
  def set_products
      @products = Product.find(params[:id])
    end


end

stuff_app/app/helpers/products_helper.rb
module ProductsHelper
end

stuff_app/app/views/products/_form.html.erb
<%= form_for(@products) do |f| %>
  <% if @products.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@products.errors.count, "error") %> prohibited this products from being saved:</h2>

      <ul>
      <% @products.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prod_name %><br>
    <%= f.text_field :prod_name%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

stuff_app/app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.prod_name %></small></h4>
      <h5><%= product.description %></small></h5>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

stuff_app/app/views/products/edit.html.erb
<h1>Editing Product</h1>


<%= render 'form' %>

<%= link_to 'Back', products_path %>

stuff_app/app/views/products/index.html.erb
<h3 class="text-center">Stuff for Sale</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

stuff_app/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

stuff_app/app/views/products/show.html.erb
<h2><%= Product %></h2>

<table class="table table-striped table-bordered">
<p>
  <b>Product:</b>
  <%= @products.prod_name %>
</p>

<p>
  <b>Description:</b>
  <%= @products.description %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency(@products.price, :unit => "$") %>
</p>

</table>


 <%= link_to "Buy #{@products.prod_name} Now!", orders_path %>




<p><%= link_to "Back to Stuff list", root_path %></p>